Feature/355 - Add strongly typed events
RoverPlatform/rover-android pull request #357
Opened 2019-05-10 14:23 UTC by samwoodall

## Description
- Add event sealed class with class for each of the event types
- Remove LocalBroadcastManager support;
- Add `addListener` method to EventEmitter that accepts an interface with a method for each event type.  eg. `fun ExperiencePresented(val experience: Experience)`.

#355

2019-05-10 17:55 UTC, orospakr requested changes

2019-05-10 17:55 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/data/events/AnalyticsService.kt
> +    private fun flattenEvent(roverEvent: RoverEvent) = mapOf<String, Any>()
This looks like it's just dropping all the contents of the RoverEvent?

2019-05-10 17:55 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/data/events/RoverEvent.kt
> +                           val campaignId: String?) : RoverEvent() {
Current source formatting style is indents of 4, not matching opening brace. I think this is the most widely accepted Kotlin code style. See https://ktlint.github.io

2019-05-10 17:55 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/data/operations/data/Experience.kt
>              }
lol. whoops 😅

2019-05-10 17:55 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/data/operations/data/Experience.kt
>              }
wait. how was the end-to-end comprehensive_experience.json test passing before??

2019-05-10 17:55 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/services/EventEmitter.kt
>   * to receive them that cannot otherwise link against types in this library.
oh this comment needs to be removed

2019-05-10 19:34 UTC, samwoodall commented on sdk/src/main/kotlin/io/rover/sdk/data/events/AnalyticsService.kt
> +    private fun flattenEvent(roverEvent: RoverEvent) = mapOf<String, Any>()
It is 😢 This is intentional and will be fixed in https://github.com/RoverPlatform/rover-android/pull/358

2019-05-13 13:40 UTC, orospakr approved these changes

2019-05-13 14:06 UTC, merged