Feature/356 - Analytics
RoverPlatform/rover-android pull request #358
Opened 2019-05-10 15:15 UTC by samwoodall

## Description
Remove asAttributes for all of the types (Experience/Row/Block etc). They will be added to Campaigns SDK separately.
Require the Analytics service to be explicitly enabled.
Serialize strongly typed Events to flat properties expected by  https://analytics.rover.io/
Remove the `keys` property from the properties sent to https://analytics.rover.io/

#356 

## Relevant Screenshots
![image](https://user-images.githubusercontent.com/20459878/57537439-42df9580-7314-11e9-9a95-193a10910208.png)
![image](https://user-images.githubusercontent.com/20459878/57537549-84704080-7314-11e9-85ae-0be11470817b.png)
![image](https://user-images.githubusercontent.com/20459878/57537578-98b43d80-7314-11e9-8d9e-46fea7d54a74.png)
![image](https://user-images.githubusercontent.com/20459878/57537646-be414700-7314-11e9-9b63-bb7e07119241.png)
![image](https://user-images.githubusercontent.com/20459878/57537664-c305fb00-7314-11e9-8df9-59ede893c983.png)
![image](https://user-images.githubusercontent.com/20459878/57537670-c7caaf00-7314-11e9-9d58-5c5b2de139a4.png)

2019-05-10 18:23 UTC, orospakr requested changes

2019-05-10 18:23 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/platform/DateExtensions.kt
> +fun Date.dateAsIso8601(): String {
Should this be `internal` visibility?

2019-05-10 18:53 UTC, samwoodall commented on sdk/src/main/kotlin/io/rover/sdk/platform/DateExtensions.kt
> +fun Date.dateAsIso8601(): String {
👍 Yeah, good catch

2019-05-13 13:42 UTC, orospakr approved these changes

2019-05-13 14:51 UTC, merged