Feature/410 - Update poll model to reflect current graphql api
RoverPlatform/rover-android pull request #415
Opened 2019-07-16 14:50 UTC by samwoodall

## Description
- Update polls model to reflect current graphql api models
- Reflect nullable and non-nullable graphql fields
- Adjust ImagePoll and TextPoll to use updated model

2019-07-22 16:44 UTC, samwoodall commented
The view, border looks good / seems to not have any negative impact, although based on testing only two experiences. More thorough testing will happen as part of polls testing

2019-07-22 16:53 UTC, orospakr requested changes

2019-07-22 16:53 UTC, orospakr commented on sdk/src/main/kotlin/io/rover/sdk/assets/ImageOptimizationService.kt
> +    fun optimizeImageBlockForFill(
`optimizeImageForFill`

Maybe add a comment that this is only for polls until such time as ImageOptimizationService is refactored to not be tightly coupled with Backgrounds.

2019-07-24 17:05 UTC, orospakr approved these changes

2019-07-24 17:40 UTC, merged