Implement Accessibility Feature
RoverPlatform/rover-android pull request #471
Opened 2020-10-30 15:06 UTC by EricDw

2020-10-30 15:18 UTC, samwoodall approved these changes
Great Stuff 👍

2020-10-30 15:18 UTC, samwoodall commented on sdk/src/main/kotlin/io/rover/sdk/ui/blocks/image/ViewImage.kt
> +                    imageView.contentDescription = binding.viewModel.accessibilityLabel
[Super Nitpick] Could be `contentDescription = binding.viewModel.accessibilityLabel` like you're doing with alpha but ignore this if you're doing it to be more explicit about what you're setting contentDesc on

2020-11-03 19:32 UTC, samwoodall commented
Just ran against an experience on staging, LGTM

2020-11-03 20:05 UTC, samwoodall requested changes
We need to change some of the `ImageOptimizationServiceSpec` code to account for the image model change. The tests won't compile because aren't passing all the required args to instantiate an `Image`,  we're missing `isDecorative` and `accessibilityLabel`

2020-11-05 01:42 UTC, EricDw commented
@samwoodall Are we ready to merge this?

2020-11-05 13:05 UTC, samwoodall commented
Yep

2020-11-05 13:06 UTC, samwoodall approved these changes

2020-11-06 23:26 UTC, merged