Merge Repos
RoverPlatform/rover-android pull request #481
Opened 2022-11-08 01:22 UTC by Moux

Merge the Rover Campaigns and Rover Experience SDK as the Rover SDK.

2022-11-09 16:42 UTC, orospakr requested changes

2022-11-09 16:42 UTC, orospakr commented on example-app/src/main/res/values/strings.xml
> +    <string name="app_name">Rover  Example App</string>
weird space here. artifact of a batch find replace?

2022-11-09 16:42 UTC, orospakr commented on example-app/src/main/res/values/constants.xml
> +    <string name="rover_uri_scheme">rv-rover-labs-inc</string>
hey it looks like I accidentally (sigh, classic) committed these settings into git.

You can revert it by just copying this version of the file over top of this one (removing "campaigns" natch) https://github.com/RoverPlatform/rover-campaigns-android/blob/49b628654b495bd9e5dcd0d06284b2f55b2fe8c1/example-app/src/main/res/values/constants.xml

2022-11-09 16:42 UTC, orospakr commented on README.md
> +    implementation "io.rover.sdk:core:4.0.0"
"3.0" at the top of this file

2022-11-09 16:42 UTC, orospakr commented on .github/workflows/ci.yml
>            DEPLOY_MAVEN_PATH: /tmp/m2
I think you missed deploy.yml.  Check the Rover Campaigns deploy.yml

2022-11-10 19:54 UTC, Moux commented on example-app/src/main/res/values/strings.xml
> +    <string name="app_name">Rover  Example App</string>
Probably.  Will fix.

2022-11-10 19:54 UTC, Moux commented on example-app/src/main/res/values/constants.xml
> +    <string name="rover_uri_scheme">rv-rover-labs-inc</string>
ok.

2022-11-10 19:55 UTC, Moux commented on README.md
> +    implementation "io.rover.sdk:core:4.0.0"
bah, will fix.

2022-11-14 15:22 UTC, orospakr requested changes

2022-11-14 15:22 UTC, orospakr commented on .github/workflows/ci.yml
>            DEPLOY_MAVEN_PATH: /tmp/m2
deploy.yml still missing

2022-11-14 15:28 UTC, Moux commented on .github/workflows/ci.yml
>            DEPLOY_MAVEN_PATH: /tmp/m2
The Rover Campaigns deploy.yml is identical to the one here, save the references ro rover-campaigns-android.

2022-11-14 15:29 UTC, Moux commented on .github/workflows/ci.yml
>            DEPLOY_MAVEN_PATH: /tmp/m2
TO be clear, there already was a deploy.yml in the master branch, and it didn't really have changes from the one in the old Rover Campaigns repo, save the references to rover-campaigns-android.   That is why it isn't in the PR.  There is no diff.

2022-11-14 15:35 UTC, Moux commented on .github/workflows/ci.yml
>            DEPLOY_MAVEN_PATH: /tmp/m2
Sorry, was wrong, the gradle line DID need changing.

2022-11-14 21:12 UTC, orospakr approved these changes

2022-11-14 22:54 UTC, merged